### ISSUE TITLE
姓、名相同时只显示一个

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#1]
切换到cas后，姓名从ldap获得。ldap中姓和名是一起保存的。如果在moodle中分开，不切实际，所以打算在数据库的firstname和lastname都保存一样的姓名。所以需要修改fullname函数，当姓和名一样时，只显示一个。

**Comment by jerray** [comment]
应该如何验证修改是否生效呢？
按照我的理解，修改了一下fullname函数的返回值。但是在页面上好像没有体现。

**Comment by sunner** [comment]
应该是firstname和lastname相同时只返回其一就行了。可以建个用户设成同名然后试试。注意函数流程中的不同分支。这个应该在流程中比较靠前的位置。

**Comment by jerray** [comment]
不很清除这个函数后半段分支的作用。不过在开头处理了一下，现在在我翻看过的页面，如果姓和名相同，那就只显示一个。

**Comment by sunner** [comment]
觉得差不多了就pull request给我。这样如果有问题，咱们可以直接在代码上comment，更直接
