### ISSUE TITLE
增加对优酷等视频网站的支持到多媒体过滤插件

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#10]
moodle/filter/mediaplugin/里是多媒体过滤插件。所有文本在显示前都会流经这个插件，它会把里面对各种视频、音频文件/网站的链接转为在线播放器，这样用户访问时就可以直接在线看。

仿照其中对youtube的支持，增加对优酷等视频网站的支持。首批先增加优酷和网易（因为它有公开课）

**Comment by jerray** [comment]
网易不给力啊，视频的缩略图另存了一个地方，与当前页面链接中的videoid没有任何关系。做了个没有缩略图的，能用。

**Comment by sunner** [comment]
还需要自己处理缩略图呀？我以为它们的swf直接就处理了呢。pull过来看看

**Comment by jerray** [comment]
网易的这个在swf里不带缩略图，在显示视频窗口的代码里，有一段是缩略图的链接。
这个我提交到我的仓库再request pull？

**Comment by sunner** [comment]
缩略图不用管，就直接用它们自己的播放器好了。
moodle仓库管理模式比较严格，所以你还是交自己仓库，然后pull给我吧。
另外，看看有没有可能把代码做得扩充性好一些，尽量能轻松增加更多的视频网站。中国视频网站太多了

**Comment by jerray** [comment]
国内视频网站做的挺乱的，每个站点都有一套自己的规则。针对每个站点都得写一个特定的正则表达式。
统一起来好像挺麻烦，我想想有没有什么比较好的扩充办法吧。
先把优酷和网易的提交了。

**Comment by jerray** [comment]
土豆的视频有单个视频，还有视频列表（豆单）。单个视频可以用类似youku那样替换videoid的形式得到播放器的代码。豆单、剧集的链接地址和其中视频的ID无关，需要使用土豆的API获取豆单中的视频的ID。要不要使用土豆的API以支持豆单和剧集？

**Comment by sunner** [comment]
API调用的就先算了。发个豆单链接，学生点链接去看也挺好
