### ISSUE TITLE
翻译Moodle Features Demo课程

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#12]
@qhan 原课程在http://demo.moodle.net/course/view.php?id=5 ，用admin，密码demo，登录后，备份下载之，然后恢复到自己的moodle 2上，在其上翻译。翻译完毕再备份打包，将来恢复到正式网站上

**Comment by dcai** [comment]
这个课程已经发布到moodle hub里了：

http://hub.moodle.org/?sesskey=2fVJV7E4Fv&_qf__course_search_form=1&downloadable=1&audience=all&educationallevel=all&subject=all&licence=all&language=en&orderby=newest&search=Features&submitbutton=Search+for+courses

**Comment by sunner** [comment]
太好了！这样下载就更容易了！

**Comment by sunner** [comment]
在三位教师的帮助下，已完成，并发布到MOOCH
