### ISSUE TITLE
自动分组

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#19]
根据已选课学生的班号和院系（user表的department和institution），自动在课程里分组。
- 以院系和班号建立小组，如果还没有该小组的话。
- 根据学生的班号和院系，加入对应的小组。
- 采用在分组页面（group/index.php?id=courseid）里加两个按钮的方式实现，一个是“按班号分组”，一个是“按院系分组”
- 按钮可被多次点击，每次点击都是把上次点击以后新加入的学生分入组中
- 界面显示的字符串可以直接写在代码里，不必使用get_string()

**Comment by sunner** [comment]
@7lemon 你来完成这个好吗？ @glovenone 还没完成zip打包下载那个。

**Comment by jerray** [comment]
好的，那我来做，木有问题。

**Comment by sunner** [comment]
语法高亮是onlinejudge的功能，不属于此issue，不要在此讨论。有专门的语法高亮库，只需整合、调用

**Comment by BookmanHan** [comment]
好的。。。我先配置上玩玩。。。
