### ISSUE TITLE
修改搜索用户的上限到300

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#2]
2.0中搜索用户，如果搜索结果数高于某值（好像是200），就不返回结果，让继续增加关键词。这使得搜索一个学院的所有学生时遇到困难。比如10803，应该返回3系所有08级学生。所以将上限提到300

**Comment by glovenone** [comment]
admin/user/lib.php   中并没有学生数200的上限，只有一个定义user数的最大上限是2000。     还要改成300么？

**Comment by sunner** [comment]
oh? 那就先忽略这个问题，做别的吧

**Comment by sunner** [comment]
此限制在不同的地方有不同的值，而且都是hardcode的。如果实现了自动分组、选课，此功能意义就不大了。暂时关闭，先不改了。
