### ISSUE TITLE
制作成绩管理的视频教程

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#27]
1. 如何加成绩项
2. 如何分类
3. 如何设权重
4. 如何设额外加分

**Comment by windwild** [comment]
sunner这个我摘了吧 一定要是视频么？

**Comment by sunner** [comment]
你还是找点儿技术活干吧。这套教程怎么弄我还没完全想好，得把大架子搭好，才能再填好内容

**Comment by windwild** [comment]
恩 行 上次我发给你的那个moodle的视频 就按那个做也可以吧 我现在在和同学做个网站 乐食网 哈哈

**Comment by sunner** [comment]
我现在不想做纯粹的视频，而是想使用moodle自身的教学功能，做一个交互式的教程，其中某些地方会用视频表现

**Comment by windwild** [comment]
ð ѧڿѧ һ ͦ˼
Ϸһ

**Comment by windwild** [comment]
恩 好吧 那下学期开学 大家一起商量商量吧 听起来挺有意思的
做游戏一样
邮件回复是乱码呀

**Comment by sunner** [comment]
图文教程已经做好，视频就先放放吧
