### ISSUE TITLE
“我毕业了”功能

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#29]
将cas账号转为本地账号，方便毕业生在毕业后，尽管cas用户已经失效，但仍能登录乐学网。

方法：
1. 将原用户名“1234567”改为“1223456.hit”
2. 将该用户认证方式从cas改为manual

做成一个独立的local模块

**Comment by sunner** [comment]
为了能让今年的毕业生用上，此功能必须在假期完成。开学后，他们的账号可能就再不能登录了

**Comment by dcai** [comment]
要是可能的话，可以让学生参与moodle tracker里的bug修复，有不少很简单的bug，这样更能增加学生的成就感，对moodle对学生的发展都有很大好处。

还有每年六月到八月会有google summer of code活动，就是google出钱让学生实现moodle的功能，如果参与bug修复多的话，有很大机会入选 :-)

**Comment by sunner** [comment]
慢慢来吧，现在这边还一个摘issue的都没有呢
在 2011-7-19 下午11:09，"dongsheng" <
reply@reply.github.com

**Comment by ghost** [comment]
这个功能意思做成cron？到每年的7月1号，自动执行完成批量修改用户名和认证方式？

**Comment by sunner** [comment]
这个想法很好！转换后发email通知学生，很有关怀感。但问题在于：
1. 不可能通过学号判断是否毕业了。留级的怎么办？
2. cron并不合适。应该是管理员每年手工执行一下。

我得问问网络中心，看看那边能否提供学生毕业的信息。如果那里能提供，就可以自动处理了。

目前还是向着自己手工操作的方向走。

**Comment by ghost** [comment]
管理员手工执行很大的工作量啊，如果能区分出毕业生，批量执行靠谱点。

**Comment by sunner** [comment]
手工执行我指的是到假期时运行一个批处理搞定一切，不是一个一个手工转换

另外想到了判断是否毕业的办法，就是看这个账号还在cas中不。毕业的、退休的、转工作的都会从cas删除，所以其实挺好判断

**Comment by ghost** [comment]
soga，俺还不太了解呢，那些认证模式也没搞清楚什么意思，只要能方便区分就好办了。

**Comment by sunner** [comment]
Finished in 2683becf45b654c49035
