### ISSUE TITLE
兼容Windows的压缩解压缩方案

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#3]
Windows上是gbk编码，linux是utf8。zip不支持字符集，导致linux和windows都不能正确解开对方压缩的含中文文件名的压缩包。
1. 建立一个rar或7z的基础压缩、解压缩库
2. 或者暂时在moodle建立zip时，根据客户端操作系统类型将文件名转编码

**Comment by sunner** [comment]
zip压缩在lib/filestorage/下实现。zip_archive是具体的zip和unzip、list等；zip_packer调用zip_archive，提供更直接的zip和unzip接口。

zip_archive已经设计了转码功能（open的最后一个参数），确实是utf-8。但zip_packer没有处理任何编码因素。

实现一套rar_archive/packer，或者7z_archive/packer并不算难。zip_packer中加上对客户端操作系统类型的判断，从而选择用不同的编码创建zip，也不难(unzip时就不能判断用户编码了)。比较麻烦的是，要修改调用者。

找机会修改一下zip_archive的缺省编码，试试它有效不

**Comment by jerray** [comment]
看了一下zip_archive，发现open方法的最后一个参数encoding并未起到实际作用。open方法仅是根据这个参数动态创建了一个encoding属性，供类中的其他方法使用。其他方法也只是调用open方法时用到encoding。所以我准备尝试在open方法内，成功打开zip文档的代码后面做一下编码转换试验。

**Comment by sunner** [comment]
这个encoding是在基类file_archive里使用的，由mangle_pathname()处理转码。zip_archive有调用mangle_pathname()。

**Comment by jerray** [comment]
噢！～忘了它是继承自file_archive的。

**Comment by jerray** [comment]
试了一下修改zip_archive的缺省编码为gbk。将文件打包以后，ubuntu下乱码，Windows下正常显示。但是发现一个问题，应该是系统的问题。即使是用utf-8编码，在我的ubuntu10.04里显示的也是乱码，拿到另一个同学的ubuntu里也是乱码，拿到一个用Fedora的同学那里就正常了。ubuntu究竟用的是什么编码呢？

**Comment by sunner** [comment]
ubuntu缺省是UTF8。用“locale”可以看当前编码。可以把两种不同编码的zip都发给我看看吗？

**Comment by jerray** [comment]
我在想moodle的备份文件是否是只有一种mbz格式呢？如果是这样的话，可以在压缩的时候判断一下压缩的文件是否为mbz，如果是就使用默认编码。如果不是，那就是zip文件了。这时候可以判断用户的系统，根据系统选择编码。我尝试了一下把zip_archive::open方法的文件名输出到文件来查看这个字符串是什么样的。zip文件的话没有后缀名，mbz文件有后缀.mbz。

**Comment by sunner** [comment]
这个想法很好！！！
我看行，就这么做吧！！！
以后遇到问题再打补丁！！！！
（咆哮体）
