### ISSUE TITLE
为“下载所有作业的zip包”增加选项

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#8]
点链接时，弹出一个javascript对话框，里面有：
1. 一个选项：包含成绩和反馈
2. 两个按钮：所有文件在同一目录下；每名用户建一个子目录

点按钮就按照对应方式打包下载，同时对话框关闭。如果勾选了“包含成绩和反馈”，就将成绩和反馈放入feedback.html，打入包内。

**Comment by glovenone** [comment]
勾选了“包含成绩和反馈”，应该是新建一个页面将成绩和反馈放入其中。 “成绩”是说老师前一次老师给出的成绩吧，初始的时候是0。但“反馈”指的是什么？

**Comment by sunner** [comment]
反馈就是老师批作业时给的评语。

现在下载的时候只包括学生上传的文件，而且没有子目录，所有文件都平铺在一起，每个文件名前加上用户的姓名。

**Comment by glovenone** [comment]
发现用户上传的作业都是单独存放到moodle之外的文件夹moodledata中的，这样做的目的是什么呢？ 防止moodle的文件夹过大？

**Comment by sunner** [comment]
moodle目录是浏览器可以访问的，而moodledata不可访问。这样就可以控制用户不能通过web直接访问文件，起到安全保护的作用。

**Comment by glovenone** [comment]
创建文件夹或者移动文件的时候在php中直接执行mkdir、cp，还是moodle有相应的函数?  新建文件夹的权限是777可以么?因为就是一个临时文件，没什么关系吧。

**Comment by sunner** [comment]
好像你不应该有这样的思路。你应该是修改那些download_submissions()，它们里面是直接调用php类实现的打包，你也要这么做。也只有这么做才能和之前那个gbk zip融洽配合。

**Comment by glovenone** [comment]
能够下载成绩和反馈信息了。我是直接把所有信息存到一个字符串里，然后用create_file_from_string传过来的，但中文乱码。用户姓名中文都是问号。        保存文件的时候将feedback.html页面编码改为utf8了，feedback内容正常显示，但下载压缩包中的用户名问号问题不知道怎么解决。这应该是前几个任务单中说的ubuntu下的乱码问题吧

**Comment by sunner** [comment]
是的，在ubuntu下载zip，文件名都是乱码，这和以前遇到的问题一样。据说是因为php的bug导致的。这个问题先不用管。

**Comment by glovenone** [comment]
终于把功能完成了,增加了按钮和选项,3种作业(online, upload, uploadsingle)都包含了进去,相应函数也单独拿了出来. 
        现在还有的一个问题就是  css没有加进去,/mod/assignment下面的那个style.css根本什么作用都没有,我用firebug看的时候发现它的css路径很奇怪,没有找到在哪.   如果要弹出框悬浮的话就要有css,不然弹出框就把下面的内容都给挤下去了
 另外选项和操作的提示不能全部汉化,就是不知道该用什么词比较好.

**Comment by sunner** [comment]
代码在哪？

**Comment by glovenone** [comment]
已经request pull了  git@github.com:glovenone/moodle.git
