### ISSUE TITLE
debian 6 on powerleader

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle#9]
@cliffwoo
在测试服务器安装debian 6。
关闭板载raid，使用LVM的软raid，测试性能。
现在使用板载raid，读取速度大约能达到150M/s这个样子。

**Comment by sunner** [comment]
@cliffwoo 这件事进度如何了？

**Comment by cliffwoo** [comment]
@sunner 这次的测试机，只有一块硬盘，没法做软raid测试，已经联系他们，让他们给再送一块了。

**Comment by sunner** [comment]
突发状况真是多啊。真是得往前赶着做啊。他们说啥时候能送到了吗？
